### ISSUE TITLE
Test run of GLOBIOM-G4M-link is repeatedly held - problem with GDXXRW?

### ISSUE THREAD

**Issue by iiasa-hinkel** [iiasa/GLOBIOM-G4M-link#4]
I am running GLOBIOM-G4M-link.Rmd.
After jobs are submitted to limpopo, they are frequently held or queued.
@andreyaugustynczik suggests this could be an error linked to GLOBIOM and to check the out files.

The relevant passage in GLOBIOM-G4M-Link\GLOBIOM_branch\Condor\test_Link\job_number.out seems to be:

```
--- . define_base.gms(907) 1224 Mb
--- call GDXXRW finaldata\BEIS_IEA_data_WEO2021_frozen.xlsx output=finaldata\BEIS_IEA_data_WEO2021_frozen_GDP.gdx Par=IEA_GDP Rng=GDP!a1:bo37 Rdim=5 Cdim=1

GDXXRW           32.2.0 rc62c018 Released Aug 26, 2020 WEI x86 64bit/MS Window
Cannot create an instance of Excel: Error = Server execution failed, ProgID: "Excel.Application"
Check that Excel is installed correctly.
In case you use the "Click-to-Run" version of Excel, uninstall
this version and install the regular version.
**** Problem opening Excel: Cannot create an instance of Excel: Error = Server execution failed, ProgID: "Excel.Application"
Total time = 142532 Ms
--- . define_base.gms(908) 1224 Mb
*** GDXIN failed E:\condor\execute\dir_10844\Model\finaldata\BEIS_IEA_data_WEO2021_frozen_GDP.gdx
*** Msg: No such file or directory
```

The problem seems related to GDXXRW.

**Comment by acjbrouwer** [comment]
@iiasa-hinkel , the issue appears to be an attempt to use GDXRRW which requires Office which is not universally available on Limpopo, and the use whereof should be avoided as it is not cross-platform. Use xl2gdx instead. For more information, see the [pertinent guidance on the GLOBIOM wiki](https://github.com/iiasa/GLOBIOM/wiki/Avoid-platform-dependent-code#do-not-call-or-execute-platform-specific-programs)

**Comment by iiasa-hinkel** [comment]
Ok, I avoided the problem by running the lines calling GDXXRW locally before running the entire GLOBIOM-G4M-link. This worked.
