### ISSUE TITLE
Condor_run_R release v2022-11-03

### ISSUE THREAD

**Issue by steffrank** [iiasa/GLOBIOM-G4M-link#8]
[Condor_run_R release v2022-11-03](https://github.com/iiasa/Condor_run_R/releases/tag/v2022-11-03) broke the GLOBIOM-G4M linking script

**Comment by acjbrouwer** [comment]
Apparently GitHub can transfer issues between repos/trackers... Learn something new every day.

**Comment by acjbrouwer** [comment]
Updated the link  (eb3b6947c0f888ccc57eb521e009f3e0afae680b) and PostProcessing submodule (3e6bf97c42e8ad042f913716626a91c8474bbbd8). An update of the DownScale submodule is pending because the HEAD revision in the DownScale repo is far ahead of the submodule reference.

**Comment by acjbrouwer** [comment]
With the recent commits the code base should work with the simplified naming of files returned via HT Condor. Things were tested up to step 4. Further testing is pending the resolution of issue #9.

**Comment by acjbrouwer** [comment]
Issues resolved
